import {
    ManageBanner,
    Dashboard,
    Profile,
    Register,
    Login,
    ManageDiscount,
    ManageCategory,
} from "pages";

var routes = [
    {
        path: "/dashboard",
        name: "Dữ liệu",
        icon: "ni ni-tv-2 text-primary",
        component: Dashboard,
        layout: "/admin",
        isProtected: true,
        isShow: true,
    },
    {
        path: "/manage-discount",
        name: "Mã giảm giá",
        icon: "fas fa-percent text-red",
        component: ManageDiscount,
        layout: "/admin",
        isProtected: true,
        isShow: true,
    },
    {
        path: "/manage-category",
        name: "Danh mục sản phẩm",
        icon: "ni ni-books text-green",
        component: ManageCategory,
        layout: "/admin",
        isProtected: true,
        isShow: true,
    },
    {
        path: "/manage-banner",
        name: "Ảnh & Banner",
        icon: "ni ni-paper-diploma text-red",
        component: ManageBanner,
        layout: "/admin",
        isProtected: true,
        isShow: true,
    },
    {
        path: "/user-profile",
        name: "Cài đặt",
        icon: "ni ni-single-02 text-yellow",
        component: Profile,
        layout: "/admin",
        isProtected: true,
        isShow: true,
    },
    {
        path: "/login",
        name: "Đăng nhập",
        icon: "ni ni-key-25 text-info",
        component: Login,
        layout: "/auth",
        isShow: false,
    },
    {
        path: "/register",
        name: "Đăng ký",
        icon: "ni ni-circle-08 text-pink",
        component: Register,
        layout: "/auth",
        isShow: false,
    },
];
export default routes;
